# Generated by Django 3.2 on 2021-07-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('post_edit_all', 'edit all fields')], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
