# Generated by Django 3.2 on 2021-04-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя автора'),
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
    ]
