# Generated by Django 3.2 on 2021-04-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='content_com',
        ),
    ]
