# Generated by Django 3.2 on 2021-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.PositiveSmallIntegerField(choices=[(1, 'happy'), (2, 'sad'), (3, 'informative'), (4, 'business')], default=1),
        ),
    ]
