# Generated by Django 3.2 on 2021-05-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_post_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mood',
        ),
    ]
